version: '3'

services:
  client:
    container_name: helx-search-client-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - $CLIENT_PORT:3000
