version: '3'

services:
  client:
    container_name: dug-search-client
    build:
      context: .
      dockerfile: Dockerfile-prod
    environment:
      DUG_URL: $DUG_URL
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    restart: always
