version: '3'

services:
  client:
    container_name: dug-search-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        REACT_APP_DUG_URL: $REACT_APP_DUG_URL
    volumes:
      - ./:/src
      - /usr/src/app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    restart: always
